repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=5000] # ~5mb

  - repo: local
    hooks:
      - id: generate-resume-pdf-basic
        name: Generate pdf/basic.pdf
        entry: just pdf-basic
        language: system
        files: (libs/.*\.typ$|templates/basic\.typ$|resume\.json$)
        pass_filenames: false

      - id: generate-resume-img-basic
        name: Generate images/basic.png
        entry: just img-basic
        language: system
        files: (libs/.*\.typ$|templates/basic\.typ$|resume\.json$)
        pass_filenames: false

      - id: generate-resume-pdf-vantage
        name: Generate pdf/vantage.pdf
        entry: just pdf-vantage
        language: system
        files: (libs/.*\.typ$|templates/vantage\.typ$|resume\.json$)
        pass_filenames: false

      - id: generate-resume-img-vantage
        name: Generate images/vantage.png
        entry: just img-vantage
        language: system
        files: (libs/.*\.typ$|templates/vantage\.typ$|resume\.json$)
        pass_filenames: false
